create table if not exists applicants (
  id bigint generated by default as identity primary key,
  "registrationCode" text unique not null,
  "fullName" text not null,
  phone text not null,
  city text,
  age text,
  position text,
  experience text,
  "workType" text,
  "callTime" text,
  message text,
  "paymentStatus" text default 'registered',
  "createdAt" timestamptz default now()
);

create index if not exists applicants_created_at_idx on applicants ("createdAt" desc);
create index if not exists applicants_phone_idx on applicants (phone);
create index if not exists applicants_registration_code_idx on applicants ("registrationCode");
